[global]
[global.window]
size = [960, 220]
title = "test_window"
[global.primary_button]
text_alignment = "top"
icon_alignment = "center"
icon_size = [64, 64]
policy = "expanding"

[power_applet]
[power_applet.environment]
dbus_mode = false
#[power_applet.window]
#size = [960, 220]
#title = "test_window"
#[power_applet.primary_button]
#text_alignment = "top"
#icon_alignment = "center"
#icon_size = [64, 64]
#policy = "expanding"
[power_applet.layout]
[[power_applet.layout.primary_buttons]]
id = "shutdown"
label = "Shutdown"
order = 1
enabled = true

[[power_applet.layout.primary_buttons]]
id = "reboot"
label = "Reboot"
order = 2
enabled = true

[[power_applet.layout.primary_buttons]]
id = "suspend"
label = "Suspend"
order = 3
enabled = true

[[power_applet.layout.primary_buttons]]
id = "hibernate"
label = "Hibernate"
order = 4
enabled = true

#[weather_applet]
#[weather_applet.window]
#size = [960, 220]
#title = "test_window"
#[weather_applet.primary_button]
#text_alignment = "top"
#icon_alignment = "center"
#icon_size = [64, 64]
#policy = "expanding"
